title: Autocatalysis
# description: This is where I share my thoughts
author: Jae S. Choi
remote_theme: zendesk/jekyll-theme-zendesk-garden@main
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
sidebar:
  - home
  - label: homeostasis
    children:
      - ecosystem_homeostasis
      - ecosystem_stability
      - ecosystem_health
  - network_theory 
  - papers
  - contact
  - about 
sidebar_label: Navigation 
search_enabled: true
auto_page_title: true
