title: Autocatalysis
# description: This is where I share my thoughts
author: Jae S. Choi
# theme: minima
minima:
  skin: solarized-dark
  nav_pages:
    - about.md
    - contact.md
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
