title: Autocatalysis
# description: This is where I share my thoughts
author: Jae S. Choi
baseurl: /autocatalysis
# theme: minima
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
