title: Autocatalysis
# description: This is where I share my thoughts
author: Jae S. Choi
remote_theme: zendesk/jekyll-theme-zendesk-garden@main
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
sidebar:
  - index
  - ecosystem_stability
  - ecosystem_health_homeostasis
  - thermodynamics
  - order
  - complexity
  - network_theory 
  - incompleteness_theorem
  - soc
  - size_spectra
  - label: Idle thoughts
    children:
      - idle_thought_1
      - idle_thought_2

sidebar_label: Navigation 
search_enabled: true
auto_page_title: true
